services:
  # Serviço para a aplicação FastAPI
  web:
    container_name: challengeee
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./backend:/app
    environment:
      PGPASSWORD: ${PGPASSWORD}
      SQLALCHEMY_DATABASE_URL: postgresql://neondb_owner:{PGPASSWORD}@ep-lively-surf-a57l4i04.us-east-2.aws.neon.tech/neondb?sslmode=require

  nginx:
    container_name: nginx-fast
    image: nginx:latest 
    volumes:
      - ./backend/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - web

