"""second connection test

Revision ID: 3e6b75bb05ac
Revises: 2f819c3e266d
Create Date: 2024-06-29 15:55:44.019444

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '3e6b75bb05ac'
down_revision: Union[str, None] = '2f819c3e266d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
