name: Challenge Tests

on:
  push:
    branches:
      - develop
jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
      name: Checkout repository
      with:
        path: backend

    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'

    - name: Add conda to system path
      run: |
        echo "$CONDA/bin" >> $GITHUB_PATH
      env:
        CONDA: /usr/local/miniconda  # Define o caminho para o Miniconda

    - name: Install Miniconda
      run: |
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
        bash Miniconda3-latest-Linux-x86_64.sh -b -p $CONDA
        conda init bash
      env:
        CONDA: /usr/local/miniconda

    - name: Install dependencies
      run: |
        conda env update --file backend/environment.yml --name base
        conda run --name base pip install flake8 pytest  # Instala flake8 e pytest no ambiente base

    - name: Lint with flake8
      run: |
        conda run --name base flake8 backend --count --select=E9,F63,F7,F82 --show-source --statistics
        conda run --name base flake8 backend --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        conda run --name base pytest backend
